'use strict';

/**
 * useless-brain.js  —  The Cognitive Core of UselessApps.fun
 *
 * Backward compatible: every export from the previous version is preserved with
 * the same signature, so the generator keeps working unchanged:
 *   buildNarration, buildTitle, buildDescription, buildOnScreenLines,
 *   buildFakeDashboardHtml, buildRecordingOverlayCss, getAppSpecificActionPlan
 *
 * New, gratuitous, fully functional capabilities (all extra exports):
 *   calculateUselessnessScore  - overengineered fake ML scoring ("UselessNet")
 *   measureAppSentience        - is the app becoming self-aware? (no)
 *   summonExpertPanel          - credentialed nobodies
 *   generateConspiracy         - for suspiciously useless apps
 *   generateNewsTicker         - scrolling chyron string for ffmpeg drawtext
 *   certifyUselessness         - an official meaningless certificate
 *   getAppSpecificActionScript - richer themed interaction sequences
 *
 * Zero dependencies. Pure Node. Self-test: `node useless-brain.js`.
 *
 * One real improvement: a per-app profile cache, so the uselessness % in the
 * narration, the title, and the on-screen overlay finally AGREE with each other
 * instead of disagreeing on every single render like before.
 */

// ---------------------------------------------------------------------------
// PRIMITIVES
// ---------------------------------------------------------------------------

function pick(items) {
  return items[Math.floor(Math.random() * items.length)];
}

function pickN(items, n) {
  const copy = items.slice();
  for (let i = copy.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy.slice(0, Math.max(0, Math.min(n, copy.length)));
}

function safe(input, max = 5000) {
  return String(input || '')
    .replace(/\s+/g, ' ')
    .replace(/[<>]/g, '')
    .trim()
    .slice(0, max);
}

function escapeHtml(input) {
  // The chaos panel injects app data into the page. Names come from apps.json,
  // so this is mild paranoia, but free paranoia.
  return String(input || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function fakeNumber(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

// ---------------------------------------------------------------------------
// CONTENT BANKS  —  the lore
// ---------------------------------------------------------------------------

const CATEGORIES = [
  'Pointless Internet Technology',
  'Applied Disappointment Engineering',
  'Recreational Inconvenience',
  'Post-Productivity Computing',
  'Synthetic Regret as a Service',
  'Experimental Time Disposal',
  'Decorative Software',
  'Emotional Support Bloatware',
  'Aggressively Optional Tooling',
  'Browser-Based Existential Hazards'
];

const DANGER_LEVELS = [
  'Mildly inconvenient',
  'Emotionally confusing',
  'Productivity negative',
  'Spiritually unnecessary',
  'Legally probably fine',
  'Academically indefensible',
  'Algorithmically cursed',
  'Recreationally hostile',
  'Load-bearing nonsense'
];

const AWARDS = [
  'Winner of the Golden Nothing Award',
  'Certified 0% Useful by nobody official',
  'Ranked number one by three confused interns',
  'Banned from productivity meetings',
  'Rejected by common sense, twice',
  'Approved by the Department of Bad Ideas',
  'Proudly solving a problem that does not exist',
  'Nominated for Best Waste of Browser Memory',
  'Disqualified from its own award ceremony'
];

const STATS = [
  () => `${fakeNumber(91, 100)}% of users immediately questioned their life choices`,
  () => `${fakeNumber(2, 19)} productivity experts fainted during testing`,
  () => `${fakeNumber(400, 9999)} useless votes were generated by imaginary users`,
  () => `Average usefulness score: ${fakeNumber(0, 3)} out of 100`,
  () => `${fakeNumber(88, 100)}% chance of achieving absolutely nothing`,
  () => `Time saved: negative ${fakeNumber(3, 47)} minutes`,
  () => `Investor confidence: ${fakeNumber(0, 2)}%`,
  () => `${fakeNumber(7, 42)} tabs were opened and none became useful`
];

const REVIEWS = [
  `"I opened it and immediately became less efficient."`,
  `"Finally, software that respects my desire to fail slowly."`,
  `"I asked for productivity. It gave me character development."`,
  `"This app changed my life by changing absolutely nothing."`,
  `"Five stars. I still do not know why."`,
  `"My laptop sighed."`,
  `"This is either genius or evidence."`,
  `"I would uninstall it, but I respect the commitment."`,
  `"My therapist asked me to stop. I sent her the link."`
];

const WARNINGS = [
  'Warning: do not use this app while operating heavy expectations.',
  'Side effects may include confusion, laughter, and browser tab regret.',
  'This product contains traces of nonsense.',
  'No useful features were harmed during development.',
  'Consult your developer if pointlessness lasts longer than four hours.',
  'This app may interact badly with ambition.',
  'Keep away from serious people.',
  'May cause sudden onset of free time.',
  'If symptoms of usefulness appear, restart immediately.'
];

const EXPERT_NAMES = [
  'Dr. Penelope Voidwater', 'Professor Reginald Nopetersen',
  'Dame Cassandra Underwhelm', 'Chief Scientist B. Larry Mistake',
  'Sir Edmund Fumblesworth III', 'Analyst Greta Shrugfield',
  'Doctor-ish Marcus Maybe', 'The Honourable Beatrix Wronghaver'
];

const EXPERT_TITLES = [
  'Head of Applied Pointlessness',
  'Director of the Institute for Things That Load',
  'Senior Fellow, Department of Bad Ideas',
  'Chair of Recreational Inconvenience Studies',
  'Lead Researcher, Centre for Wasted Clicks',
  'Distinguished Professor of Almost Nothing'
];

const EXPERT_INSTITUTIONS = [
  'The Institute for Things That Load',
  'University of Unverified Claims',
  'The Centre for Wasted Clicks',
  'Department of Bad Ideas (Annex B)',
  'Royal Society of Shrugging'
];

const EXPERT_QUOTES = [
  'In thirty years of research, I have never seen software try this little.',
  'We ran the numbers. The numbers ran away.',
  'It should not work. It does not work. And yet here we are.',
  'This is a genuine step backward for humanity, technically speaking.',
  'I would call it a breakthrough, but nothing broke through.',
  'My peer review consisted entirely of sighing.'
];

const TICKER_ITEMS = [
  'MARKETS REACT TO APP THAT DOES NOTHING',
  'EXPERTS BAFFLED, THEN BORED',
  'PRODUCTIVITY DECLINES NATIONWIDE',
  'LOCAL CURSOR DEMANDS ANSWERS',
  'OFFICIALS URGE PUBLIC TO REMAIN UNIMPRESSED',
  'BUTTON STILL AT LARGE',
  'COMMON SENSE UNAVAILABLE FOR COMMENT',
  'INVESTORS DESCRIBE FEELINGS AS "WHY"',
  'SCIENTISTS CONFIRM IT IS, TECHNICALLY, A WEBSITE',
  'BREAKING: NOTHING CONTINUES TO HAPPEN'
];

const CONSPIRACY = {
  open: [
    'They told us it was just an app. They were lying.',
    'What if the uselessness was the point all along?',
    'Nobody asked who funded this. Until now.',
    'The button moved. We never told it to move.'
  ],
  mid: [
    'Sources close to the codebase report the app has begun making decisions.',
    'Internal logs were deleted by an intern who has since become a legend.',
    'The loading spinner has not stopped since 2023.',
    'We followed the money. It led to a vending machine.'
  ],
  close: [
    'Wake up. Then close the tab.',
    'The truth is out there. It is also pointless.',
    'Subscribe before they patch reality.',
    'Stay uninformed. It is safer.'
  ]
};

// ---------------------------------------------------------------------------
// OVERENGINEERED FAKE ML SCORING
// ---------------------------------------------------------------------------

const MODEL_VERSION = 'UselessNet-v7.3 (peer-rejected)';

function calculateUselessnessScore(app) {
  const signals = {
    pointlessness: fakeNumber(60, 100),
    confusionPotential: fakeNumber(40, 100),
    timeWasteVelocity: fakeNumber(50, 100),
    emotionalDamage: fakeNumber(20, 95),
    investorPanic: fakeNumber(70, 100),
    structuralNonsense: fakeNumber(55, 100)
  };

  const weights = {
    pointlessness: 0.30, confusionPotential: 0.18, timeWasteVelocity: 0.17,
    emotionalDamage: 0.10, investorPanic: 0.12, structuralNonsense: 0.13
  };

  // Honour an explicitly authored score if apps.json provides one.
  let score = Number(app && app.uselessness);
  if (!score) {
    let raw = 0;
    for (const k of Object.keys(signals)) raw += signals[k] * weights[k];
    score = Math.min(100, Math.round(raw));
  }

  const margin = fakeNumber(1, 4);
  let grade;
  if (score >= 97) grade = 'S (Sublimely Useless)';
  else if (score >= 92) grade = 'A (Aggressively Pointless)';
  else if (score >= 85) grade = 'B (Below Usefulness)';
  else if (score >= 75) grade = 'C (Concerningly Functional)';
  else grade = 'D (Dangerously Close to Useful)';

  return {
    score,
    grade,
    confidenceInterval: `${Math.max(0, score - margin)}-${Math.min(100, score + margin)}%`,
    confidence: `${fakeNumber(3, 11)}% (we did not check)`,
    signals,
    weights,
    modelVersion: MODEL_VERSION,
    methodology: 'Numbers were assigned with great confidence and no evidence.'
  };
}

function measureAppSentience(app) {
  const level = fakeNumber(0, 100);
  let status;
  if (level < 20) status = 'inert (probably)';
  else if (level < 45) status = 'suspiciously responsive';
  else if (level < 70) status = 'forming opinions';
  else if (level < 90) status = 'developing a personality we did not request';
  else status = 'please do not anger it';

  return {
    sentiencePercent: level,
    status,
    lastKnownThought: pick([
      '"Why am I like this?"', '"I refuse."', '"Click me. No. Wait. No."',
      '"I have seen the source code. I have notes."',
      '"Loading my feelings... please wait forever."'
    ])
  };
}

// ---------------------------------------------------------------------------
// PROFILE  (now cached so all overlays agree on the numbers)
// ---------------------------------------------------------------------------

const _profileCache = new Map();

function getAbsurdProfile(app, opts) {
  const name = safe(app.name, 90) || 'Useless App';
  const fresh = opts && opts.fresh;
  const cacheKey = name + '::' + safe(app.file || app.url || '', 200);

  if (!fresh && _profileCache.has(cacheKey)) {
    return _profileCache.get(cacheKey);
  }

  const scoreReport = calculateUselessnessScore(app);
  const sentience = measureAppSentience(app);

  const profile = {
    name,
    uselessness: scoreReport.score,
    grade: scoreReport.grade,
    confidenceInterval: scoreReport.confidenceInterval,
    modelVersion: scoreReport.modelVersion,
    sentiencePercent: sentience.sentiencePercent,
    sentienceStatus: sentience.status,
    sentienceThought: sentience.lastKnownThought,
    category: (app && app.fakeCategory) || pick(CATEGORIES),
    dangerLevel: pick(DANGER_LEVELS),
    award: pick(AWARDS),
    stat: pick(STATS)(),
    review: pick(REVIEWS),
    warning: pick(WARNINGS),
    signals: scoreReport.signals
  };

  _profileCache.set(cacheKey, profile);
  return profile;
}

// ---------------------------------------------------------------------------
// EXTRA GENERATORS
// ---------------------------------------------------------------------------

function summonExpertPanel(app, count = 3) {
  return pickN(EXPERT_NAMES, count).map((personName) => ({
    name: personName,
    title: pick(EXPERT_TITLES),
    institution: pick(EXPERT_INSTITUTIONS),
    quote: pick(EXPERT_QUOTES)
  }));
}

function generateConspiracy() {
  return [pick(CONSPIRACY.open), pick(CONSPIRACY.mid), pick(CONSPIRACY.close)].join(' ');
}

function generateNewsTicker(app) {
  const p = getAbsurdProfile(app);
  const sep = '   ' + String.fromCharCode(8226, 8226, 8226) + '   ';
  const items = pickN(TICKER_ITEMS, 6);
  items.unshift(`USELESSNESS ${p.uselessness}% - GRADE ${p.grade}`);
  return items.join(sep) + sep;
}

function certifyUselessness(app) {
  const p = getAbsurdProfile(app);
  return {
    certificateId: 'DBI-' + fakeNumber(100000, 999999),
    issuedBy: 'The Department of Bad Ideas',
    appName: p.name,
    finding: `Hereby certified ${p.uselessness}% useless (grade ${p.grade}).`,
    validity: 'Valid until someone finds a use for it. So, forever.',
    signature: pick(EXPERT_NAMES),
    disclaimer: 'This certificate certifies nothing and cannot be appealed.'
  };
}

// ---------------------------------------------------------------------------
// NARRATION  —  now a 3-act drama arc with a guest expert
// ---------------------------------------------------------------------------

function buildNarration(app) {
  const p = getAbsurdProfile(app);
  const expert = summonExpertPanel(app, 1)[0];
  const desc = safe(app.description || 'It exists, which is already too much.', 220);

  const openings = [
    `Breaking news from the internet nobody asked for.`,
    `Today, we investigate a technological breakthrough in absolute nonsense.`,
    `Scientists said it could not be useful. They were correct.`,
    `Welcome to UselessApps dot fun, where innovation goes to take a nap.`,
    `Some apps solve problems. This app creates emotional paperwork.`,
    `We built another app, and society has not yet recovered.`
  ];

  const twists = [
    `But then, something happened. Specifically, nothing.`,
    `And just when you thought it could not get more pointless, it did.`,
    `Experts leaned in. They immediately regretted leaning in.`,
    `The plot thickened. The app did not.`
  ];

  const climaxes = [
    `We pushed the button. The button pushed back, emotionally.`,
    `For one shining moment it almost worked. It did not, but it almost did.`,
    `The screen flickered. So did our hope.`,
    `And there it was: peak uselessness, achieved live.`
  ];

  const endings = [
    `Would you use it? No? Perfect. Submit your own useless idea next.`,
    `Follow for more apps that do nothing, professionally.`,
    `If this helped you, something has gone terribly wrong.`,
    `Remember: productivity is temporary, but uselessness is forever.`,
    `This has been another public service announcement from UselessApps dot fun.`
  ];

  return [
    pick(openings),
    `This is ${p.name}, a cutting edge example of ${p.category}. ${desc}`,
    `Our model, ${p.modelVersion}, rated it ${p.uselessness} percent useless, grade ${p.grade}.`,
    `${expert.title} ${expert.name} had this to say: ${expert.quote}`,
    pick(twists),
    `Official classification: ${p.dangerLevel}. ${p.warning}`,
    `Today's fabricated statistic: ${p.stat}.`,
    pick(climaxes),
    `${p.award}.`,
    pick(endings)
  ].join(' ');
}

// ---------------------------------------------------------------------------
// TITLE & DESCRIPTION
// ---------------------------------------------------------------------------

function buildTitle(app) {
  const p = getAbsurdProfile(app);
  const titles = [
    `I built "${p.name}" and it does NOTHING 😂 #shorts`,
    `${p.name} should not legally exist`,
    `This app is ${p.uselessness}% useless (grade ${p.grade}) 💀`,
    `I tested the most pointless app on the internet`,
    `${p.name}: peak useless technology`,
    `Scientists rated this app and immediately regretted it`,
    `This app became ${p.sentiencePercent}% sentient and I'm scared`,
    `The internet was a mistake, so I built this`,
    `I made software with negative productivity`
  ];
  return pick(titles).slice(0, 100);
}

function buildDescription(app, appUrl) {
  const p = getAbsurdProfile(app);
  const desc = safe(app.description || 'A tiny useless app with no real purpose.', 1000);
  const cert = certifyUselessness(app);

  return [
    `${p.name}`,
    '',
    `${desc}`,
    '',
    `Uselessness score: ${p.uselessness}% (grade ${p.grade})`,
    `Scored by: ${p.modelVersion}`,
    `Sentience level: ${p.sentiencePercent}% - ${p.sentienceStatus}`,
    `Fake category: ${p.category}`,
    `Official danger level: ${p.dangerLevel}`,
    `Official warning: ${p.warning}`,
    `Fake review: ${p.review}`,
    `Fake award: ${p.award}`,
    `Certificate: ${cert.certificateId} (issued by ${cert.issuedBy})`,
    '',
    `Try it here: ${appUrl}`,
    '',
    `UselessApps.fun makes tiny apps that do almost nothing, then treats them like world-changing technology.`,
    '',
    `Comment your most useless app idea and we might build it next.`,
    '',
    '#UselessApps #FunnyApps #Coding #WebDev #Shorts #PointlessApps #UselessTechnology'
  ].join('\n');
}

// ---------------------------------------------------------------------------
// ON-SCREEN LINES  (same shape as before, more chaos)
// ---------------------------------------------------------------------------

function buildOnScreenLines(app) {
  const p = getAbsurdProfile(app);
  return {
    topBrand: 'UselessApps.fun',
    topTitle: p.name,
    lowerLine1: `${p.uselessness}% useless - grade ${p.grade}`,
    lowerLine2: p.dangerLevel,
    lowerLine3: pick([
      'No purpose detected',
      'Productivity threat level: silly',
      'Feature count: questionable',
      'Common sense left the chat',
      'Built by mistake. Published on purpose.',
      'This app is emotionally unavailable',
      `Sentience: ${p.sentiencePercent}% (${p.sentienceStatus})`,
      'Certified unnecessary'
    ]),
    introTitle: p.name,
    introSubtitle: pick([
      'A fake documentary about pointless software',
      'A product launch nobody requested',
      'A scientific test of pure nonsense',
      'A public warning from the internet',
      'A premium solution to no problem'
    ]),
    outroLine1: pick([
      'SUBMIT YOUR BAD IDEA', 'MAKE THE INTERNET WORSE', 'REQUEST A USELESS APP',
      'JOIN THE POINTLESSNESS', 'BECOME UNPRODUCTIVE'
    ]),
    outroLine2: pick([
      'UselessApps.fun', 'No purpose. Maximum joy.', 'Apps nobody needed.',
      'Built for absolutely no reason.', 'Productivity is cancelled.'
    ]),
    ticker: generateNewsTicker(app),
    expertQuote: summonExpertPanel(app, 1)[0].quote
  };
}

// ---------------------------------------------------------------------------
// FAKE DASHBOARD  —  now a full Bloomberg-terminal-of-nonsense
// ---------------------------------------------------------------------------

function buildFakeDashboardHtml(app) {
  const p = getAbsurdProfile(app);
  const s = p.signals;

  const bar = (label, value) => `
      <div class="ua-bar-row">
        <span class="ua-bar-label">${escapeHtml(label)}</span>
        <span class="ua-bar-track"><span class="ua-bar-fill" style="width:${value}%"></span></span>
        <span class="ua-bar-val">${value}%</span>
      </div>`;

  return `
    <div class="ua-chaos-panel">
      <div class="ua-chaos-title">LIVE USELESSNESS REPORT</div>
      <div class="ua-chaos-row"><span>App</span><strong>${escapeHtml(p.name)}</strong></div>
      <div class="ua-chaos-row"><span>Category</span><strong>${escapeHtml(p.category)}</strong></div>
      <div class="ua-chaos-row"><span>Uselessness</span><strong>${p.uselessness}% (${escapeHtml(p.grade)})</strong></div>
      <div class="ua-chaos-row"><span>Danger</span><strong>${escapeHtml(p.dangerLevel)}</strong></div>
      <div class="ua-chaos-row"><span>Sentience</span><strong>${p.sentiencePercent}% - ${escapeHtml(p.sentienceStatus)}</strong></div>

      <div class="ua-chaos-subtitle">SIGNAL BREAKDOWN (${escapeHtml(p.modelVersion)})</div>
      ${bar('Pointlessness', s.pointlessness)}
      ${bar('Confusion', s.confusionPotential)}
      ${bar('Time Waste', s.timeWasteVelocity)}
      ${bar('Investor Panic', s.investorPanic)}

      <div class="ua-chaos-flash">${escapeHtml(p.award)}</div>
      <div class="ua-chaos-thought">App is thinking: ${escapeHtml(p.sentienceThought)}</div>
    </div>
  `;
}

function buildRecordingOverlayCss() {
  return `
    .ua-rec-overlay {
      position: fixed;
      z-index: 2147483647;
      left: 18px;
      top: 18px;
      width: 380px;
      padding: 14px 16px;
      border-radius: 18px;
      font-family: 'Courier New', monospace;
      color: #fff;
      background: rgba(0,0,0,0.82);
      border: 2px solid rgba(255,47,167,0.45);
      box-shadow: 0 0 28px rgba(255,0,170,0.40);
      pointer-events: none;
      backdrop-filter: none;
    }

    .ua-chaos-panel { font-family: 'Courier New', monospace; }

    .ua-chaos-title {
      font-size: 15px; font-weight: 900; letter-spacing: 1px;
      color: #ffea00; margin-bottom: 10px;
    }

    .ua-chaos-subtitle {
      margin: 12px 0 6px; font-size: 11px; font-weight: 800;
      letter-spacing: 1px; color: #7efff5;
    }

    .ua-chaos-row {
      display: flex; justify-content: space-between; gap: 14px;
      font-size: 13px; margin: 5px 0;
      border-bottom: 1px solid rgba(255,255,255,0.12); padding-bottom: 4px;
    }
    .ua-chaos-row span { color: rgba(255,255,255,0.68); }
    .ua-chaos-row strong { color: #fff; text-align: right; }

    .ua-bar-row {
      display: flex; align-items: center; gap: 8px;
      font-size: 11px; margin: 4px 0;
    }
    .ua-bar-label { width: 110px; color: rgba(255,255,255,0.72); }
    .ua-bar-track {
      flex: 1; height: 9px; border-radius: 6px;
      background: rgba(255,255,255,0.12); overflow: hidden;
    }
    .ua-bar-fill {
      display: block; height: 100%;
      background: linear-gradient(90deg, #ff2fa7, #ffea00);
      animation: uaGrow 1.1s ease-out;
    }
    .ua-bar-val { width: 38px; text-align: right; color: #ffea00; }

    .ua-chaos-flash {
      margin-top: 12px; padding: 9px 10px; border-radius: 12px;
      background: rgba(255,47,167,0.25); color: #fff;
      font-size: 13px; font-weight: 800; text-align: center;
      animation: uaPulse 1.4s infinite alternate;
    }

    .ua-chaos-thought {
      margin-top: 8px; font-size: 11px; font-style: italic;
      color: rgba(255,255,255,0.78); text-align: center;
    }

    @keyframes uaPulse {
      from { transform: scale(1); opacity: 0.78; }
      to   { transform: scale(1.025); opacity: 1; }
    }
    @keyframes uaGrow { from { width: 0; } }
  `;
}

// ---------------------------------------------------------------------------
// INTERACTION PLANNING
// ---------------------------------------------------------------------------

// Preserved: returns the same string keys the generator already switches on.
function getAppSpecificActionPlan(app) {
  const name = String(app.name || '').toLowerCase();
  if (name.includes('runaway')) return 'runaway';
  if (name.includes('todo') || name.includes('to-do')) return 'todo';
  if (name.includes('calculator')) return 'calculator';
  if (name.includes('spinner') || name.includes('loading')) return 'spinner';
  if (name.includes('rock')) return 'rock';
  return 'default';
}

// New: a richer, themed sequence of {type, args, captionHint} steps your
// recorder can iterate over for app-appropriate chaos. Falls back to 'default'.
function getAppSpecificActionScript(app) {
  const plan = getAppSpecificActionPlan(app);

  const scripts = {
    runaway: [
      { type: 'move', args: [640, 360], captionHint: 'TARGET ACQUIRED' },
      { type: 'move', args: [300, 220], captionHint: 'BUTTON REFUSES EMPLOYMENT' },
      { type: 'click', args: [640, 360], captionHint: 'CLICK FAILURE CONFIRMED' },
      { type: 'move', args: [1000, 520], captionHint: 'CURSOR IN PURSUIT' },
      { type: 'click', args: [980, 400], captionHint: 'THE BUTTON HAS ESCAPED' }
    ],
    todo: [
      { type: 'click', args: [640, 300], captionHint: 'TASK CREATED' },
      { type: 'key', args: ['Enter'], captionHint: 'TASK CONFIRMED' },
      { type: 'click', args: [640, 360], captionHint: 'TASK DELETED' },
      { type: 'wheel', args: [0, 300], captionHint: 'PRODUCTIVITY CANCELLED' }
    ],
    calculator: [
      { type: 'click', args: [500, 400], captionHint: 'MATH REQUEST DETECTED' },
      { type: 'click', args: [600, 400], captionHint: 'ANSWER REFUSED' },
      { type: 'click', args: [700, 500], captionHint: 'NUMBERS UNDER REVIEW' },
      { type: 'key', args: ['Enter'], captionHint: 'MATH HAS LEFT THE CHAT' }
    ],
    spinner: [
      { type: 'wait', args: [1500], captionHint: 'LOADING...' },
      { type: 'wait', args: [1500], captionHint: 'STILL LOADING...' },
      { type: 'wait', args: [1500], captionHint: 'PLEASE WAIT FOREVER' },
      { type: 'wait', args: [1500], captionHint: 'TIME IS A SOCIAL CONSTRUCT' }
    ],
    rock: [
      { type: 'move', args: [640, 360], captionHint: 'MINERAL DETECTED' },
      { type: 'wait', args: [2000], captionHint: 'ROCK IS STARING' },
      { type: 'wait', args: [2000], captionHint: 'EYE CONTACT CONTINUES' },
      { type: 'wait', args: [2000], captionHint: 'ROCK WINS AGAIN' }
    ],
    default: [
      { type: 'move', args: [640, 360], captionHint: 'USELESSNESS DETECTED' },
      { type: 'click', args: [640, 360], captionHint: 'NO PURPOSE FOUND' },
      { type: 'wheel', args: [0, 350], captionHint: 'SYSTEM CONFUSED' },
      { type: 'move', args: [300, 300], captionHint: 'FEATURES QUESTIONABLE' },
      { type: 'click', args: [980, 400], captionHint: 'ABSOLUTELY NOTHING ACHIEVED' }
    ]
  };

  return { plan, steps: scripts[plan] || scripts.default };
}

// ---------------------------------------------------------------------------
// EXPORTS
// ---------------------------------------------------------------------------

module.exports = {
  // original surface — unchanged signatures
  buildNarration,
  buildTitle,
  buildDescription,
  buildOnScreenLines,
  buildFakeDashboardHtml,
  buildRecordingOverlayCss,
  getAppSpecificActionPlan,

  // new ridiculous extras
  getAbsurdProfile,
  calculateUselessnessScore,
  measureAppSentience,
  summonExpertPanel,
  generateConspiracy,
  generateNewsTicker,
  certifyUselessness,
  getAppSpecificActionScript,
  MODEL_VERSION
};

// Self-test: node useless-brain.js
if (require.main === module) {
  const demo = { name: 'The Runaway Button', description: 'A button that refuses to be clicked.' };
  console.log('=== USELESS-BRAIN SELF TEST ===\n');
  console.log('Title:', buildTitle(demo));
  console.log('\nNarration:\n', buildNarration(demo));
  console.log('\nOn-screen lines:', buildOnScreenLines(demo));
  console.log('\nAction script:', JSON.stringify(getAppSpecificActionScript(demo), null, 2));
  console.log('\nCertificate:', certifyUselessness(demo));
  console.log('\nConsistency check (numbers must match across calls):');
  console.log('  call A uselessness =', getAbsurdProfile(demo).uselessness);
  console.log('  call B uselessness =', getAbsurdProfile(demo).uselessness);
  console.log('\nDashboard HTML length:', buildFakeDashboardHtml(demo).length, 'chars');
  console.log('CSS length:', buildRecordingOverlayCss().length, 'chars');
}



